version: '3.3'

services:

  python-app:
    build:
      context: ./app
      dockerfile: Dockerfile_redis
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
