version: '3.3'

services:

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis:6.2.5
    ports:
      - 6379:6379

volumes:
  redis-data:
